Rodapé
seedabit/SeedComercial pull request #12
Opened 2021-09-07 20:45 UTC by LucasAraujoBR

criei o rodapé de acordo com o protótipo, quebrei para mobile com 800x de tela, usei imagens que catei na web... assim que me mandarem as oficiais, assim como o número de telefone, eu substituo. Aguardo retorno

2021-09-08 17:39 UTC, dEgito requested changes
Dale boy, entonces... Vai precisar mexer numas coisinhas:
1) Por algum motivo a fonte não tá pegando... Isso tá rolando em todas as branchs, tenta reimportar na tua local
2) Tu pode pegar as imagens oficiais no próprio figma (tu seleciona a imagem e no final da barra direta tem a opção "Export")
3)E por último, o background: tem o degrdê tá ligado? Tu tbm consegue pegar o código pelo figma (Seleciona o background, vai em Inspect e ele te dá o código do CSS)

2021-09-09 12:19 UTC, LucasAraujoBR commented
Dani mudei as imagens... algo aconteceu no bg que ficou estranho, n entendi bem.
Outra coisa, eu já tinha feito a parte desktop fora da media query, **preciso** trocar ou posso deixar assim ?

2021-09-09 15:38 UTC, LucasAraujoBR commented
apliquei mobile first, botei a quebra em 900px.

2021-09-09 19:44 UTC, dEgito requested changes
Ôpa mano, a responsividade tá massa, só tem uma coisita:

Tá rolando alguma coisa no bg da div da imagem, tá vendo a diferença das cores?
Eu acredito que seja uma configuração do global style (tem uma parada de background: #fffff que tá bugando as paradas, vê se é isso)

![image](https://user-images.githubusercontent.com/75611712/132752109-7d8bd87e-7773-4973-91d2-3bb93af6ed2f.png)

2021-09-09 19:57 UTC, LucasAraujoBR commented
Salve, peguei esse style do protótipo:
`--Color-Rodape: linear-gradient(180deg, #0e3789 0%, rgba(14, 55, 137, 0.74) 100%);`

2021-09-09 20:12 UTC, LucasAraujoBR commented
Dani consegui arrumar, mas ta com um probleminha 
![mobiledani](https://user-images.githubusercontent.com/68979111/132755715-187cf59b-f07a-4f70-b32b-c53cb63fbe70.png)
o logo da seed ta com essa borda branca, não sei pq
a parte desktop ta pronta:
![desktopdani](https://user-images.githubusercontent.com/68979111/132755782-65fb152e-e058-462c-96ea-bde13dfc576c.png)

2021-09-09 20:24 UTC, LucasAraujoBR commented
terminei de ajustar o bg @dEgito

2021-09-10 21:48 UTC, dEgito approved these changes
Topíssimo boy

2021-09-11 00:52 UTC, merged